version: "3"

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379

  db:
    image: postgres:10.3-alpine
    container_name: db
    # network_mode: host
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=comunion2020
      - POSTGRES_PASSWORD=comunion2020
      - POSTGRES_DB=comunion

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command:  server /data
